name: "Verify PR"

on:
  pull_request:

env:
  NODE_VERSION: 20.x

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Set Node.js ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install dependencies
        run: |
          npm install

      - name: Run npm build
        run: |
          npm run build
        # env:
        #   NODE_ENV: 'production'
